version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pokerchips-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pokerchips
      POSTGRES_USER: joel
      POSTGRES_PASSWORD: secret123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
